import json
import os
from datetime import datetime
from browser_env import (
    create_id_based_action,
    create_id_based_actions,
    StateInfo,
    Trajectory,
    ActionTypes,
    ScriptBrowserEnv
)
from evaluation_harness.evaluators import evaluator_router
from AgentOccam.obs_opt import (
    prune_tree,
    translate_node_to_str,
)
from AgentOccam.gherkin_parser import parse_gherkin, gherkin_to_objective
from AgentOccam.ax_trace_recorder import AXTraceRecorder


class WebArenaEnvironmentWrapper():
    def __init__(self, config_file, max_browser_rows=300, max_steps=50, slow_mo=1, observation_type="accessibility_tree", current_viewport_only=False, viewport_size={"width": 1280, "height": 720}, headless=False, global_config=None):
        self.webarena_env = ScriptBrowserEnv(
                    headless=headless,
                    slow_mo=slow_mo,
                    observation_type=observation_type,
                    current_viewport_only=current_viewport_only,
                    viewport_size=viewport_size,
                    global_config=global_config
                )
        self.config_file = config_file
        with open(self.config_file, "r", encoding="utf-8") as f:
            self.config = json.load(f)
        self.global_config = global_config
        
        self.obs, self.info = self.webarena_env.reset(options={"config_file": self.config_file})
        self.terminated = False
        
        # Support both traditional "intent" and Gherkin format
        if "gherkin" in self.config:
            # Parse Gherkin scenario to natural language objective
            gherkin_scenario = parse_gherkin(self.config)
            self.objective = gherkin_scenario.to_natural_language()
            self.gherkin_scenario = gherkin_scenario
            self.acceptance_criteria = gherkin_scenario.get_acceptance_criteria()
        elif "intent" in self.config:
            # Traditional intent format
            self.objective = self.config["intent"]
            self.gherkin_scenario = None
            self.acceptance_criteria = []
        else:
            raise ValueError("Task config must contain either 'intent' or 'gherkin' field")

        # ISP task: append a strict constraint so the agent does NOT try to
        # "fix" deliberate test-case inputs (e.g. empty or invalid values).
        if "isp_test_case" in self.config:
            self.is_isp_task = True
            isp_block = self.config["isp_test_case"]
            expected = isp_block.get("_expected", "unknown")
            self.objective += (
                "\n\n[ISP TEST MODE] "
                "The input values above are fixed test data generated by Input Space Partitioning. "
                "You MUST fill in every field with exactly the value specified — "
                "do NOT change, correct, or substitute any value, even if it looks wrong or empty. "
                "After you have attempted to submit the form, stop immediately and report the system's response. "
                f"The expected outcome for this test case is: '{expected}' "
                "(i.e., the system should " +
                ("accept the input and complete the action." if expected == "pass"
                 else "reject the input or show a validation/error message.") +
                ") Report faithfully what actually happened."
            )
        else:
            self.is_isp_task = False
        
        self.url = self.config["start_url"]
        self.max_browser_rows = max_browser_rows
        self.max_steps = max_steps
        self.steps = 0
        self.is_done = False
        self.reward = 0.0
        self._isp_screenshot_saved = False
        self.isp_screenshot_path = None
        self.evaluation_comment = ""
        self.evaluation_comments = []
        task_name = self.config.get("task_id") or os.path.splitext(os.path.basename(self.config_file))[0]
        self.ax_trace_recorder = AXTraceRecorder(task_name)
        
        self.trajectory: Trajectory = []
        self.update_webarena_metrics()
        self._capture_ax_trace()
        
    def reset(self):
        self.obs, self.info = self.webarena_env.reset(options={"config_file": self.config_file})
        self._isp_screenshot_saved = False
        self.isp_screenshot_path = None
        self.evaluation_comment = ""
        self.evaluation_comments = []
        self.ax_trace_recorder = AXTraceRecorder(self.config.get("task_id") or os.path.splitext(os.path.basename(self.config_file))[0])
        self._capture_ax_trace()

    def close(self):
        self.webarena_env.close()
        
    def get_url(self):
        return self.url
    
    def get_objective(self):
        return self.objective 
    
    def get_gherkin_scenario(self):
        """Get the original Gherkin scenario object if available"""
        return self.gherkin_scenario
    
    def get_acceptance_criteria(self):
        """Get acceptance criteria from Gherkin scenario"""
        return self.acceptance_criteria
    
    def get_sites(self):
        return self.config["sites"]
        
    # 觀察
    def observation(self): 
        self.url = self.webarena_env.page.url
        if self.global_config and hasattr(self.global_config.env, 'prune') and self.global_config.env.prune:
            root_node = self.obs["text"][1]
            DOM_root_node = prune_tree(objective=self.objective, root_node=root_node, mode="node")
            DOM_str = translate_node_to_str(node=DOM_root_node, mode="concise")
            return {"text": DOM_str, "image": self.obs["image"], "node": DOM_root_node}
        else:
            browser_content = self.obs["text"][0]
            browser_content = browser_content.split("\n")[:self.max_browser_rows] 
            browser_content = "\n".join(browser_content)
            return browser_content
    
    def done(self):
        if self.is_done:
            return True
        return False
    
    def status(self):
        status = {'done': self.is_done, 'reward': self.reward, 'success': float(self.reward > 0), 'num_actions': self.steps}
        if self.isp_screenshot_path:
            status['isp_screenshot_path'] = self.isp_screenshot_path
        if self.evaluation_comment:
            status['evaluation_comment'] = self.evaluation_comment
        return status

    def _save_isp_screenshot_if_needed(self):
        """Save a final-page screenshot for manual ISP result verification."""
        if self._isp_screenshot_saved:
            return
        if "isp_test_case" not in self.config:
            return
        try:
            abs_config_path = os.path.abspath(self.config_file)
            marker = f"{os.sep}config_files{os.sep}"
            if marker in abs_config_path:
                workspace_root = abs_config_path.split(marker, 1)[0]
            else:
                workspace_root = os.path.dirname(abs_config_path)
            out_dir = os.path.join(workspace_root, "output", "isp_manual_review")
            os.makedirs(out_dir, exist_ok=True)

            task_id = self.config.get("task_id", "task")
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            screenshot_name = f"{task_id}_{timestamp}.png"
            screenshot_path = os.path.join(out_dir, screenshot_name)

            self.webarena_env.page.screenshot(path=screenshot_path, full_page=True)
            self.isp_screenshot_path = screenshot_path
            if isinstance(self.info, dict):
                self.info["isp_screenshot_path"] = screenshot_path
            print(f"[ISP] Manual review screenshot saved: {screenshot_path}")
        except Exception as e:
            print(f"[ISP] Failed to save manual review screenshot: {e}")
        finally:
            self._isp_screenshot_saved = True

    def _capture_ax_trace(self):
        try:
            self.ax_trace_recorder.capture(self.webarena_env.page)
        except Exception as e:
            print(f"[AXTrace] Failed to capture accessibility trace: {e}")
    
    def step(self, action):
        self.steps = self.steps + 1
        print(f"[Step {self.steps}] {action}")
        print("*"*100)
        if self.steps > self.max_steps:
            print(f"Steps {self.steps} exceeded maximum {self.max_steps}")
            self.is_done = True
            action_cmd = create_id_based_action(f"stop [Trajectory failed: Steps {self.steps} exceeded maximum {self.max_steps}.]")
            self.update_webarena_metrics(action_cmd)
            return self.status()

        if action is None or action == "":
            action_cmds = []
        else:
            try:
                action_cmds = create_id_based_actions(action)
                if not action_cmds:
                    return False
            except Exception as e:
                print(f"Invalid action syntax: {e}")
                action_cmds = []

        for action_cmd in action_cmds:
            try:
                self.obs, _, self.terminated, _, self.info = self.webarena_env.step(action_cmd) 
                self.update_webarena_metrics(action_cmd)
                if action_cmd["action_type"] not in {ActionTypes.STOP, ActionTypes.NONE}:
                    self._capture_ax_trace()
            except Exception as e:
                print(f"Error occurred while taking step: {e}")
            
        return self.status()
    
    def update_webarena_metrics(self, action_cmd=None):
        # Append action (if any) and resulting sate
        if action_cmd:
            self.trajectory.append(action_cmd)
            if action_cmd["action_type"]== ActionTypes.STOP:
                self.is_done = True

        if not self.is_done: # If we are done, no need to append state
            state_info: StateInfo = {"observation": self.obs, "info": self.info}
            self.trajectory.append(state_info)
            
        if self.is_done:    
            self._save_isp_screenshot_if_needed()
            try:
                evaluator = evaluator_router(self.config_file)
                self.reward = evaluator(trajectory=self.trajectory, config_file=self.config_file, page=self.webarena_env.page, client=self.webarena_env.get_page_client(self.webarena_env.page))
                self.evaluation_comment = getattr(evaluator, "evaluation_comment", "")
                self.evaluation_comments = getattr(evaluator, "evaluation_comments", [])
            except Exception as e:
                print(f"Got excepetion: {e}")
                self.reward = 0
